### ISSUE TITLE
Error when calling trainer.fit() in Bert4Rec/SasRec examples (Python 3.8.10)

### ISSUE THREAD

**Issue by lilya-vasilyeva** [sb-ai-lab/RePlay#72] opened 2024-05-24 06:12 UTC
To reproduce:
Using python 3.8.10 kernel execute examples/09_sasrec_example.ipynb (or examples/10_bert4rec_example.ipynb) [release/v0.16.0 branch]
->
On the fitting stage the error occurs: "collections.OrderedDict" object has no attribute 'name'
![image](https://github.com/sb-ai-lab/RePlay/assets/38869170/8c2b4e57-b998-4849-8c3b-683df2bf9805)

**Comment by OnlyDeniko** [comment] 2024-06-06 05:42
I'm closing it because it's not reproducible

**Closed by OnlyDeniko** 2024-06-06 05:42 UTC
Labels: bug
